---
# tasks file for ruby - Debian/Ubuntu Family

- name: Debian/Ubuntu Family | Installing {{ ruby_app_debian_package }}
  ansible.builtin.package:
    name: "{{ ruby_app_debian_package }}"
    state: "{{ ruby_desired_state }}"
    force_apt_get: yes
    update_cache: yes
