---
# tasks file for ruby - EL Family

- name: EL Family | Installing epel-release
  package:
    name: epel-release
    state: present
    update_cache: yes

- name: EL Family | Installing {{ ruby_app_el_package }}
  package:
    name: "{{ ruby_app_el_package }}"
    state: "{{ ruby_desired_state }}"
    update_cache: yes
