---
# tasks file for ruby - CentOS

- name: Installing epel-release on EL systems
  package:
    name: epel-release
    state: present
    update_cache: yes
- name: Installing "{{ ruby_app_el_package }}" on EL systems
  package:
    name: "{{ ruby_app_el_package }}"
    state: "{{ ruby_desired_state }}"
    update_cache: yes
